### ISSUE TITLE
Get "nothing changed, not updating cache" for changed path

### ISSUE THREAD

**Issue by ono** [travis-ci/casher#17]
At lostmy.name, we are having troubles with caching on Travis that is causing the slowness of our builds. It seems that there is a problem if you specify multiple directories.

```yml
language: ruby
cache:
  bundler: true
  directories:
    - node_modules
```

```yml
language: ruby
cache:
  directories:
    - vendor/bundle
    - node_modules
```

In both cases, it caches only one directory (the later one added as a cache directories).

I've reviewed the source code and found some suspicious logic:
https://github.com/travis-ci/casher/blob/master/bin/casher

1. @mtime_file is not saved when `md5deep_available?` is true so next time the script is executed @mtimes is initialised
2. md5deep overwrite file instead of appending: https://github.com/travis-ci/casher/blob/master/bin/casher#L82

I haven't debugged properly so those points might be irrelevant. In that case, please contact me on github DM so I can provide our private repo information if needed.
